apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig
  namespace: reactapp
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: "ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92Mi8iOiB7CiAgICAKICAgICAgImF1dGgiOiAiZG1WdWRXSm9ZWEpoWkhkaGFqcFhaV3hqYjIxbE1USWoiCiAgICB9CiAgfQp9"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactcalcapp
  namespace: reactapp
spec:
  selector:
    matchLabels:
      app: reactcalcapp
  template:
    metadata:
      labels:
        app: reactcalcapp
    spec:
      containers:
        - name: reactcalcapp
          image: venubharadwaj/reactapps:0.3
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "400m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          ports:
          - containerPort: 300        
      imagePullSecrets:
        - name: dockerconfig
---
apiVersion: v1
kind: Service
metadata:
  name: reactcalcapp
  namespace: reactapp
spec:
  selector:
    app: reactcalcapp 
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
  
 

